using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public static class ShopContainer
{
    //WeaponStatHolderBase(System.Type wepType,
    //float wepDamage, float wepRange, float wepInnacuracy, float wepFireRate, float wepShotLifetime,
    //float wepShotWidth, int weaponCost = 0, string wepNickname = "Nameless",
    //    /*minigun vars*/float mini_wepStartFireRate = 0.0f, float mini_wepTimeToRevUp = 0.0f, float mini_wepCoolDownSpeed = 0.0f,
    //    /*shotgun vars*/int shot_wepShotCount = 0,
    //    /*assault vars*/float ass_wepInitInaccuracy = 0.0f
    //    )
    public static List<WeaponStatHolderBase> weaponsForSale = new List<WeaponStatHolderBase> {
        new WeaponStatHolderBase(typeof(Weapon_AssRifle),
            wepDamage : 10,
            wepRange : 30,
            wepInnacuracy : 2,
            wepFireRate : 3,
            wepShotLifetime : 0.1f,
            wepShotWidth : 0.1f,
            weaponCost : 750,
            wepColour : new Color(0.180f, 0.282f, 1),
            crystalMultiplier : 1.0f,
            wepNickname : "Heavy Hitter"),
        new WeaponStatHolderBase(typeof(Weapon_AssRifle),
            wepDamage : 5,
            wepRange : 30,
            wepInnacuracy : 2,
            wepFireRate : 5,
            wepShotLifetime : 0.1f,
            wepShotWidth : 0.1f,
            weaponCost : 1000,
            wepColour : new Color(0.180f, 0.282f, 1),
            crystalMultiplier : 1.5f,
            wepNickname : "Average Joey"),
        new WeaponStatHolderBase(typeof(Weapon_AssRifle), 
            wepDamage : 5, 
            wepRange : 30, 
            wepInnacuracy : 2, 
            wepFireRate : 10, 
            wepShotLifetime : 0.05f, 
            wepShotWidth : 0.02f, 
            weaponCost : 1500,
            wepColour : Color.red,
            crystalMultiplier : 1.0f,
            wepNickname : "Speedy Rifle"),
        new WeaponStatHolderBase(typeof(Weapon_Shotgun), 
            wepDamage : 5, 
            wepRange : 5, 
            wepInnacuracy : 70, 
            wepFireRate : 0.5f, 
            wepShotLifetime : 0.1f, 
            wepShotWidth : 0.1f, 
            weaponCost : 500,
            wepColour : Color.cyan,
            crystalMultiplier : 2.0f,
            wepNickname : "Short n' Shotty", 
            shot_wepShotCount : 15),
        new WeaponStatHolderBase(typeof(Weapon_Shotgun),
            wepDamage : 3,
            wepRange : 10,
            wepInnacuracy : 50,
            wepFireRate : 2f,
            wepShotLifetime : 0.1f,
            wepShotWidth : 0.1f,
            weaponCost : 1000,
            wepColour : new Color(0.937f, 0.078f, 1),
            crystalMultiplier : 1.5f,
            wepNickname : "Steve",
            shot_wepShotCount : 10),
        new WeaponStatHolderBase(typeof(Weapon_Shotgun),
            wepDamage : 5,
            wepRange : 15,
            wepInnacuracy : 90,
            wepFireRate : 1f,
            wepShotLifetime : 0.1f,
            wepShotWidth : 0.1f,
            weaponCost : 5000,
            wepColour : new Color(0.811f, 0.309f, 0.309f),
            crystalMultiplier : 2f,
            wepNickname : "Big Bertha",
            shot_wepShotCount : 50),
        new WeaponStatHolderBase(typeof(Weapon_Shotgun),
            wepDamage : 3,
            wepRange : 999,
            wepInnacuracy : 180,
            wepFireRate : 999f,
            wepShotLifetime : 0.01f,
            wepShotWidth : 0.1f,
            weaponCost : 9999,
            wepColour : new Color(0,0,0),
            crystalMultiplier : 10f,
            wepNickname : "ThisMightCrashYourGame_Shotgun",
            shot_wepShotCount : 100),
        new WeaponStatHolderBase(typeof(Weapon_MiniGun), 
            wepDamage : 5, 
            wepRange : 25, 
            wepInnacuracy : 20, 
            wepFireRate : 20, 
            wepShotLifetime : 0.1f, 
            wepShotWidth : 0.1f, 
            weaponCost: 500,
            wepColour : Color.magenta,
            crystalMultiplier : 0.5f,
            wepNickname : "Mini Boy", 
            mini_wepStartFireRate : 1, 
            mini_wepTimeToRevUp : 10, 
            mini_wepCoolDownSpeed : 3),
        new WeaponStatHolderBase(typeof(Weapon_MiniGun),
            wepDamage : 2,
            wepRange : 25,
            wepInnacuracy : 20,
            wepFireRate : 50,
            wepShotLifetime : 0.1f,
            wepShotWidth : 0.1f,
            weaponCost: 1000,
            wepColour : new Color(0.972f, 1, 0.078f),
            crystalMultiplier : 1.0f,
            wepNickname : "Slow n' Steady",
            mini_wepStartFireRate : 1,
            mini_wepTimeToRevUp : 30,
            mini_wepCoolDownSpeed : 5)
        };
}
